# Generated by Django 6.0 on 2025-12-17 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='date_observation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'observation"),
        ),
        migrations.AlterField(
            model_name='observation',
            name='notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
