# Generated by Django 6.0 on 2025-12-18 11:15

import django.core.validators
import django.db.models.deletion
import faunatrack.models
from django.conf import settings
from django.db import migrations, models

def delete_duplicate_especes(apps, schema_editor):
    Espece = apps.get_model('faunatrack', 'Espece')
    # Find names that appear more than once
    duplicate_noms = (
        Espece.objects
        .values('nom')
        .annotate(count=models.Count('id'))
        .filter(count__gt=1)
        .values_list('nom', flat=True)
    )
    # For each duplicate name, keep only the first one
    for nom in duplicate_noms:
        duplicates = list(Espece.objects.filter(nom=nom).order_by('created_at'))
        # Delete all but the first one
        for dupe in duplicates[1:]:
            dupe.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0002_alter_observation_date_observation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_especes),
        migrations.AlterField(
            model_name='espece',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[faunatrack.models.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='observation',
            name='espece',
            field=models.ManyToManyField(related_name='observations', to='faunatrack.espece'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='quantite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='profilscientifique',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_scientifique', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='profil_scientifique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='faunatrack.profilscientifique'),
        ),
        migrations.AlterField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='faunatrack.project'),
        ),
    ]
