# Generated by Django 6.0 on 2025-12-18 12:58

import django.db.models.deletion
from django.db import migrations, models


def migrate_m2m_to_fk(apps, schema_editor):
    """Copy first espece from M2M to the new FK field."""
    Observation = apps.get_model('faunatrack', 'Observation')
    for observation in Observation.objects.all():
        # Get the first espece from the M2M relationship
        first_espece = observation.espece.first()
        if first_espece:
            observation.espece_new = first_espece
            observation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0003_alter_espece_nom_alter_location_latitude_and_more'),
    ]

    operations = [
        # Step 1: Update model options
        migrations.AlterModelOptions(
            name='espece',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.AlterModelOptions(
            name='observationphotos',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.AlterModelOptions(
            name='profilscientifique',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['-created_at'], 'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        
        # Step 2: Add a NEW FK field with a different name
        migrations.AddField(
            model_name='observation',
            name='espece_new',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.PROTECT, 
                related_name='observations_new', 
                to='faunatrack.espece'
            ),
        ),
        
        # Step 3: Migrate data from M2M to FK
        migrations.RunPython(migrate_m2m_to_fk, migrations.RunPython.noop),
        
        # Step 4: Remove the M2M field
        migrations.RemoveField(
            model_name='observation',
            name='espece',
        ),
        
        # Step 5: Rename the new FK field to 'espece'
        migrations.RenameField(
            model_name='observation',
            old_name='espece_new',
            new_name='espece',
        ),
    ]
