# Generated by Django 6.0 on 2025-12-18 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0004_alter_espece_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espece',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='observationphotos',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='profilscientifique',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectmembership',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='observation',
            name='espece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='faunatrack.espece'),
        ),
    ]
