# Generated by Django 6.0 on 2025-12-18 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faunatrack', '0005_alter_espece_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='espece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='faunatrack.espece'),
        ),
    ]
